apiVersion: v1
kind: Service
metadata:
  name: {{ template "atlassian-jira.fullname" . }}
  labels:
    app: {{ template "atlassian-jira.name" . }}
    chart: {{ template "atlassian-jira.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    #- port: {{ .Values.service.port }}
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ template "atlassian-jira.name" . }}
    release: {{ .Release.Name }}
